In [1]:
# Instalações

In [2]:
# Importações
import pandas as pd

In [3]:
data = pd.Series([1, 2, 3, 4, 5])

In [4]:
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
data.values

array([1, 2, 3, 4, 5])

In [6]:
data[1]

np.int64(2)

In [7]:
data[1:3]

1    2
2    3
dtype: int64

In [8]:
populacao_ne = {
    'Fortaleza': 2428678,
    'Salvador' : 2418005,
    'Recife' : 1488920,
    'São Luís' : 1037775,
    'Maceió' : 957916,
    'Teresina' : 866300,
    'João Pessoa' : 833932
}

In [ ]:
populacao = pd.Series(populacao_ne)
populacao

Fortaleza      2428678
Salvador       2418005
Recife         1488920
São Luís       1037775
Maceió          957916
Teresina        866300
João Pessoa     833932
dtype: int64

In [10]:
populacao.values

array([2428678, 2418005, 1488920, 1037775,  957916,  866300,  833932])

In [11]:
populacao[2:4]

Recife      1488920
São Luís    1037775
dtype: int64

In [ ]:
lista_exemplo = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 0]
]

In [13]:
pop_ne = [2418005, 1488920, 833932]
area = [692.818, 218.843, 211.745]

In [14]:
dict_ne = {
    "pop_ne": pop_ne,
    "area": area
}

In [15]:
dict_ne

{'pop_ne': [2418005, 1488920, 833932], 'area': [692.818, 218.843, 211.745]}

In [16]:
# pd.DataFrame({
#     "pop_ne": pop_ne,
#     "area": area
# })

data_ne = pd.DataFrame(dict_ne)

In [17]:
data_ne

    pop_ne     area
0  2418005  692.818
1  1488920  218.843
2   833932  211.745

In [18]:
data_ne.columns

Index(['pop_ne', 'area'], dtype='object')

In [20]:
data_ne['pop_ne']

0    2418005
1    1488920
2     833932
Name: pop_ne, dtype: int64

In [23]:
data_ne.head(2)

    pop_ne     area
0  2418005  692.818
1  1488920  218.843

In [24]:
data_ne.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   pop_ne  3 non-null      int64
 1   area    3 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 180.0 bytes

In [25]:
data_ne.shape

(3, 2)

In [26]:
print(data_ne.shape[0])
print(data_ne.shape[1])

3
2

In [28]:
data_ne['area'].unique()

array([692.818, 218.843, 211.745])

In [29]:
data_ne['pop_ne'].nunique()

3

In [31]:
data_ne['pop_ne'].value_counts()

pop_ne
2418005    1
1488920    1
833932     1
Name: count, dtype: int64

In [32]:
data_ne.count()

pop_ne    3
area      3
dtype: int64

In [33]:
data_ne['area'].sum()

np.float64(1123.406)

In [34]:
data_ne['pop_ne'].max()

2418005

In [35]:
data_ne['pop_ne'].min()

833932

In [36]:
data_ne.describe()

             pop_ne        area
count  3.000000e+00    3.000000
mean   1.580286e+06  374.468667
std    7.959790e+05  275.721452
min    8.339320e+05  211.745000
25%    1.161426e+06  215.294000
50%    1.488920e+06  218.843000
75%    1.953462e+06  455.830500
max    2.418005e+06  692.818000